baseurl: "http://brunsgaard.io/"
title: brunsgaard.io
theme: ghostwriter
languageCode: en-us
copyright: Jonas Brunsgaard
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Jonas Brunsgaard
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Thoughts and Writings
  description: ""
  github: "https://github.com/brunsgaard"
  linkedin: "https://linkedin.com/in/XXX/"
  # twitter: "https://twitter.com/jonasbrunsgaard"
  # email: jonas.brunsgaard@gmail.com
  opengraph: true
  shareTwitter: true
  rss: false
  shareFacebook: false
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    # - name: Projects
    #   url: /project/
    #   weight: 2
    # - name: Contact
    #   url: /page/contact/
    #   weight: 3
    # - name: About
    #   url: /page/about/
    #   weight: 4
